- arguments:
    [
      -XGHC2024,
      -XDuplicateRecordFields,
      -XNoFieldSelectors,
      -XOverloadedRecordDot,
      -XStrictData,
    ]

- group: { name: future, enabled: true }
- group: { name: extra, enabled: true }

- extensions:
    - default: false
    - name:
        - AllowAmbiguousTypes
        - OverloadedStrings
        - PatternSynonyms
        - RequiredTypeArguments
        - TemplateHaskell
        - TypeData
        - ViewPatterns

- ignore: { name: "Use lambda-case" }
- ignore: { name: "Use drop1" }
