- arguments:
    [
      -XGHC2024,
      -XDuplicateRecordFields,
      -XNoFieldSelectors,
      -XOverloadedRecordDot,
      -XStrictData,
    ]

- group: { name: future, enabled: true }
- group: { name: dollar, enabled: true }

- extensions:
    - default: false
    - name:
        - AllowAmbiguousTypes
        - BinaryLiterals
        - DeriveAnyClass
        - NoStarIsType
        - OverloadedStrings
        - PatternSynonyms
        - RequiredTypeArguments
        - TemplateHaskell
        - TypeData
        - ViewPatterns

- ignore: { name: "Use lambda-case" }
