name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - uses: cachix/install-nix-action@v31.11.0
      - uses: cachix/cachix-action@v17
        with:
          name: henrytill
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L .#all -o result-all

  linux-flake-static:
    needs: linux-flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - uses: cachix/install-nix-action@v31.11.0
      - uses: cachix/cachix-action@v17
        with:
          name: henrytill
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L .#all-static -o result-all-static
      - uses: actions/upload-artifact@v7
        with:
          name: hbt-x86_64-unknown-linux-musl
          path: result-all-static/bin/hbt
      - uses: actions/upload-artifact@v7
        with:
          name: pinboard-client-x86_64-unknown-linux-musl
          path: result-all-static/bin/pinboard-client

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
